### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [AnkitRupal/BrainTumorDetectionUsingDeepLearning#3]
Dear authors: 
    Recently I  have a looking at your this project and feel interested in it !  I am interested in this project, but I also face some challenges.  and I wish I could receive your suggestion from your guide.. 
  The question is that I could not find the dataset used in this project?  And I konw,
"Kaggle BR35H dataset for training
 used another dataset from Kaggle itself having just 253 images    "
And how could I get them?  And My e-mqil is: 1814707618@qq.com.
 Any suggestion or recommendation is appreciated.
Thank you. I am looking forward to your reply Sincerely!

Best regards.

**Comment by AnkitRupal** [comment]
Hey, you can find the dataset over this link: https://www.kaggle.com/datasets/ahmedhamada0/brain-tumor-detection
Just see in the summary and you can see the 1500 images over there. You just need to download the dataset, that's it :)
Hope this helps!
